import { describe, it, expect } from "vitest";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

// Phase 01b §5: the storefront must never render a raw <img> for a Media
// object — that bypasses the webp/avif variants generated by media-optimize
// and ships the (heavier) original. Everything goes through
// <ResponsiveImage>, which is the one place allowed to use a real <img>.
const STOREFRONT_DIRS = [
  path.join(__dirname, "../../src/app/[locale]"),
  path.join(__dirname, "../../src/components/storefront"),
];
const ALLOWED_RAW_IMG_FILES = ["responsive-image.tsx"];

async function collectFiles(dir: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await collectFiles(full)));
    else if (/\.(tsx|ts)$/.test(entry.name)) files.push(full);
  }
  return files;
}

describe("storefront never renders a raw <img> (Phase 01b §5)", () => {
  it("only responsive-image.tsx contains a literal <img tag", async () => {
    const offenders: string[] = [];
    for (const dir of STOREFRONT_DIRS) {
      for (const file of await collectFiles(dir)) {
        if (ALLOWED_RAW_IMG_FILES.includes(path.basename(file))) continue;
        const content = await readFile(file, "utf8");
        if (/<img[\s/>]/.test(content)) offenders.push(file);
      }
    }
    expect(offenders).toEqual([]);
  });
});
